name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  ## What's Changed
  
  $CHANGES
  
  ## 📦 Downloads
  
  Download the appropriate installer for your platform:
  
  ### 🪟 Windows
  - **Installer (Recommended)**: [Pasta_$RESOLVED_VERSION_x64-setup.exe](https://github.com/utensils/pasta/releases/download/v$RESOLVED_VERSION/Pasta_$RESOLVED_VERSION_x64-setup.exe)
  - **MSI Package**: [Pasta_$RESOLVED_VERSION_x64_en-US.msi](https://github.com/utensils/pasta/releases/download/v$RESOLVED_VERSION/Pasta_$RESOLVED_VERSION_x64_en-US.msi)
  
  > **Note**: May trigger antivirus warnings due to keyboard emulation. This is expected behavior.
  
  ### 🍎 macOS
  - **Intel Macs**: [Pasta_$RESOLVED_VERSION_x64.dmg](https://github.com/utensils/pasta/releases/download/v$RESOLVED_VERSION/Pasta_$RESOLVED_VERSION_x64.dmg)
  - **Apple Silicon (M1/M2/M3)**: [Pasta_$RESOLVED_VERSION_aarch64.dmg](https://github.com/utensils/pasta/releases/download/v$RESOLVED_VERSION/Pasta_$RESOLVED_VERSION_aarch64.dmg)
  
  > **Important**: macOS builds are unsigned. You'll need to:
  > 1. Right-click the app and select "Open" on first launch, or
  > 2. Remove quarantine: `xattr -d com.apple.quarantine /Applications/Pasta.app`
  > 
  > The app requires accessibility permissions for keyboard emulation.
  
  ### 🐧 Linux
  - **AppImage (Universal)**: [pasta-tray_$RESOLVED_VERSION_amd64.AppImage](https://github.com/utensils/pasta/releases/download/v$RESOLVED_VERSION/pasta-tray_$RESOLVED_VERSION_amd64.AppImage)
  - **Debian/Ubuntu**: [pasta-tray_$RESOLVED_VERSION_amd64.deb](https://github.com/utensils/pasta/releases/download/v$RESOLVED_VERSION/pasta-tray_$RESOLVED_VERSION_amd64.deb)
  - **Fedora/RHEL**: [pasta-tray-$RESOLVED_VERSION-1.x86_64.rpm](https://github.com/utensils/pasta/releases/download/v$RESOLVED_VERSION/pasta-tray-$RESOLVED_VERSION-1.x86_64.rpm)
  
  > **GNOME Users**: Install system tray support:
  > ```bash
  > # Ubuntu/Debian
  > sudo apt install gnome-shell-extension-appindicator
  > # Fedora
  > sudo dnf install gnome-shell-extension-appindicator
  > ```
  > Or install from [GNOME Extensions](https://extensions.gnome.org/extension/615/appindicator-support/)
  
  **Full Changelog**: https://github.com/utensils/pasta/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🔧 CI/CD'
    labels:
      - 'ci'
      - 'cd'
      - 'github-actions'
  - title: '⬆️ Dependencies'
    labels:
      - 'dependencies'
      - 'deps'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

exclude-labels:
  - 'skip-changelog'

autolabeler:
  - label: 'chore'
    title:
      - '/^chore/i'
  - label: 'bug'
    title:
      - '/^fix/i'
  - label: 'enhancement'
    title:
      - '/^feat/i'
  - label: 'documentation'
    title:
      - '/^docs/i'
  - label: 'ci'
    title:
      - '/^ci/i'
  - label: 'dependencies'
    title:
      - '/^(chore|fix)\(deps\)/i'