name: Release Notes

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
      - '.gitignore'
      - 'flake.nix'
      - 'flake.lock'
      - '.envrc'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/*.yml'
      - '!.github/workflows/release-notes.yml'
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
      - '.gitignore'
      - 'flake.nix'
      - 'flake.lock'
      - '.envrc'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/*.yml'
      - '!.github/workflows/release-notes.yml'

permissions:
  contents: read
  pull-requests: write

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}